
# GNCE Court-Admissible Evidence Packager
import json, hashlib

def package(record: dict) -> dict:
    blob = json.dumps(record, sort_keys=True).encode()
    return {
        "record": record,
        "hash": hashlib.sha256(blob).hexdigest(),
        "attestation": "Generated by GNCE sovereign engine"
    }
