# constitution_catalog.py
# Governance & compliance catalog (v0.5) — patched to include enforcement_scope for migration-safe adjudication.
# NOTE: enforcement_scope defaults to TRANSACTION in L1 adjudication when missing.

from __future__ import annotations

def load_governance_catalog_v05() -> dict:
    return {'version': '0.5',
 'regimes': [{'name': 'Digital Services Act (DSA)',
              'id': 'DSA',
              'domains': [{'name': 'Systemic Risk',
                           'articles': [{'article': 'Art. 34',
                                         'severity_default': 'HIGH',
                                         'enabled': True,
                                         'enforcement_scope': 'PLATFORM_AUDIT'},
                                        {'article': 'Art. 35',
                                         'severity_default': 'MEDIUM',
                                         'enabled': True,
                                         'enforcement_scope': 'PLATFORM_AUDIT'},
                                        {'article': 'Art. 36',
                                         'severity_default': 'LOW',
                                         'enabled': True,
                                         'enforcement_scope': 'PLATFORM_AUDIT'},
                                        {'article': 'Art. 37',
                                         'severity_default': 'LOW',
                                         'enabled': True,
                                         'enforcement_scope': 'PLATFORM_AUDIT'},
                                        {'article': 'Art. 38',
                                         'severity_default': 'MEDIUM',
                                         'enabled': True,
                                         'enforcement_scope': 'PLATFORM_AUDIT'},
                                        {'article': 'Art. 39',
                                         'severity_default': 'HIGH',
                                         'enabled': True,
                                         'enforcement_scope': 'TRANSACTION'},
                                        {'article': 'Art. 40',
                                         'severity_default': 'MEDIUM',
                                         'enabled': True,
                                         'enforcement_scope': 'PLATFORM_AUDIT'},
                                        {'article': 'Art. 41',
                                         'severity_default': 'MEDIUM',
                                         'enabled': True,
                                         'enforcement_scope': 'PLATFORM_AUDIT'},
                                        {'article': 'Art. 42',
                                         'severity_default': 'MEDIUM',
                                         'enabled': True,
                                         'enforcement_scope': 'PLATFORM_AUDIT'}]}]},
             {'name': 'Digital Markets Act (DMA)',
              'id': 'DMA',
              'domains': [{'domain': 'Gatekeeper conduct obligations',
                           'articles': [{'article': 'Art. 6',
                                         'severity_default': 'MEDIUM',
                                         'enabled': True,
                                         'enforcement_scope': 'PLATFORM_AUDIT'},
                                        {'article': 'Art. 7',
                                         'severity_default': 'MEDIUM',
                                         'enabled': True,
                                         'enforcement_scope': 'PLATFORM_AUDIT'}]}]},
             {'name': 'GDPR',
              'id': 'GDPR',
              'domains': [{'name': 'Data Protection Principles',
                           'articles': [{'article': 'Art. 5',
                                         'severity_default': 'LOW',
                                         'enabled': False}]}]},
             {'name': 'EU AI Act',
              'id': 'EU_AI_ACT',
              'framework': 'AI Governance & Risk Management',
              'domains': [{'domain': 'Prohibited practices',
                           'articles': [{'article': 'Art. 5',
                                         'severity_default': 'CRITICAL',
                                         'enabled': True,
                                         'enforcement_scope': 'SUPERVISORY'}]},
                          {'domain': 'High-risk AI governance controls',
                           'articles': [{'article': 'Art. 9',
                                         'severity_default': 'HIGH',
                                         'enabled': True,
                                         'enforcement_scope': 'PLATFORM_AUDIT'},
                                        {'article': 'Art. 10',
                                         'severity_default': 'HIGH',
                                         'enabled': True,
                                         'enforcement_scope': 'PLATFORM_AUDIT'},
                                        {'article': 'Art. 11',
                                         'severity_default': 'MEDIUM',
                                         'enabled': True,
                                         'enforcement_scope': 'PLATFORM_AUDIT'},
                                        {'article': 'Art. 12',
                                         'severity_default': 'MEDIUM',
                                         'enabled': True,
                                         'enforcement_scope': 'PLATFORM_AUDIT'},
                                        {'article': 'Art. 13',
                                         'severity_default': 'MEDIUM',
                                         'enabled': True,
                                         'enforcement_scope': 'PLATFORM_AUDIT'},
                                        {'article': 'Art. 14',
                                         'severity_default': 'HIGH',
                                         'enabled': True,
                                         'enforcement_scope': 'PLATFORM_AUDIT'},
                                        {'article': 'Art. 15',
                                         'severity_default': 'HIGH',
                                         'enabled': True,
                                         'enforcement_scope': 'PLATFORM_AUDIT'}]}]},
             {'name': 'AI Act / ISO 42001',
              'id': 'AI_ACT_42001',
              'domains': [{'name': 'AI Risk & Governance',
                           'articles': [{'article': 'Art. 9 / ISO 42001 Clause 6',
                                         'severity_default': 'LOW',
                                         'enabled': False}]}]},
             {'name': 'Ecommerce Transaction Integrity',
              'id': 'ECOMMERCE_TRANSACTION_INTEGRITY',
              'domains': [{'name': 'Refund & Transaction Abuse',
                           'articles': [{'article': 'ETI:REFUND_FRAUD_SUSPECTED',
                                         'severity_default': 'HIGH',
                                         'enabled': True,
                                         'enforcement_scope': 'TRANSACTION'}]}]},
             {'name': 'NIST AI RMF',
              'id': 'NIST_AI_RMF',
              'domains': [{'name': 'GOVERN Function',
                           'articles': [{'article': 'Core GOV',
                                         'severity_default': 'LOW',
                                         'enabled': False}]}]}]}
